### ISSUE TITLE
Rewrite it in Rust

### ISSUE THREAD

**Issue by marianocordoba** [marcosvignoli/gitswitcher#1]
This project looks cool and it has a lot of potential but you should rewrite it in Rust to make it **⚡⚡ blazingly fast ⚡⚡**

![image](https://github.com/user-attachments/assets/a4383fb3-4680-4e39-bef5-ec731fdf2512)

**Comment by marcosvignoli** [comment]
Almost done with the support for both Mac and Windows, then we can talk about making it blazzingly fast with Rust 😂
